{
  description = "wallpaper.studio.ui — browser editor for bgsvg configs (toolchain, plus the renderer it consumes)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    # The renderer, pinned by flake.lock. The .wasm, its generated .d.ts and
    # descriptor.bin must all come from ONE revision: tools/drift.ts compares
    # the descriptor against src/schema.ts, and a descriptor from a different
    # revision than the module was built from proves nothing. The lockfile is
    # what guarantees that: package.json's `types` script vendors the .d.ts,
    # the .js and the .wasm into vendor/, but only ever out of the BGSVG_WASM
    # this shell exports, so vendor/ cannot come from a revision the lock does
    # not name.
    #
    # Changes upstream reach this repository only once pushed; adopt them with
    #   nix flake update wallpaper-studio-svg
    # For co-development against a local working tree, without touching the lock:
    #   nix develop --override-input wallpaper-studio-svg path:../wallpaper.studio.svg
    # Hyphens, not the repository's own dots: nix rejects a dotted input name
    # in --override-input.
    wallpaper-studio-svg.url = "git+ssh://git@github.com/M4jor-Tom/wallpaper.studio.svg.git";
    wallpaper-studio-svg.inputs.nixpkgs.follows = "nixpkgs";

    # node_modules inside the sandbox, out of bun.lock alone -- packages.site
    # needs it, because vite and tsc *are* the build. It reads bun.nix, a
    # committed translation of bun.lock, and the two must agree: a package
    # bun.lock names and bun.nix omits is missing from the install cache, and
    # the sandboxed `bun install` does not fail on it, it hangs retrying a
    # fetch that no network will ever answer. So bun.nix is not regenerated by
    # hand. package.json's `postinstall` rewrites it on every `bun install`,
    # which is the only thing that can change bun.lock in the first place; the
    # devShell carries the bun2nix that does the rewriting, and outside it the
    # script is a no-op, since a checkout nobody has installed into cannot
    # drift.
    bun2nix.url = "github:nix-community/bun2nix";
    bun2nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, wallpaper-studio-svg, bun2nix }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAll = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # A server and a window that die together: close the window and the
      # server stops, ^C and the window goes. Both editors want this, and they
      # differ only in what `serve` is -- darkhttpd over a built site, or vite
      # over a checkout.
      #
      # The window is surf: a bare WebKitGTK view, no tabs, no toolbar,
      # ~280 MiB. Not vite's own --open, which hands the URL to $BROWSER
      # (normally the very firefox this avoids) and spawns it detached, leaving
      # nothing to tie the two together. Telling surf the URL instead means
      # pinning one first: IPv4, because vite's default listens on [::1] alone,
      # which the readiness probe could never reach.
      windowed =
        pkgs:
        { name, port, serve, query ? "" }:
        if pkgs.stdenv.hostPlatform.isLinux then
          ''
            if (exec 3<>/dev/tcp/127.0.0.1/${port}) 2>/dev/null; then
              # the probe cannot tell our server from anyone else's, so a port
              # already held would open a window onto it and wait
              echo "${name}: 127.0.0.1:${port} is already in use" >&2
              exit 1
            fi
            ${serve} &
            server=$!
            until (exec 3<>/dev/tcp/127.0.0.1/${port}) 2>/dev/null; do
              kill -0 "$server" 2>/dev/null ||
                { echo "${name}: server exited before it was listening" >&2; exit 1; }
              sleep 0.1
            done
            ${pkgs.surf}/bin/surf 'http://127.0.0.1:${port}/${query}' &
            window=$!
            # backgrounded so the shell waits in `wait`, where it still runs
            # traps: a foreground child defers them until it exits, which is
            # the one moment they are no use
            trap 'kill "$server" "$window" 2>/dev/null' EXIT INT TERM
            wait "$window"
          ''
        else
          ''
            # no window here: surf is X11/GTK, and nothing else is light
            echo "${name}: http://127.0.0.1:${port}/${query}"
            exec ${serve}
          '';
    in
    {
      # The editor as something you can install: a site built in the sandbox,
      # served from the store. No checkout, no node_modules, no bun at runtime
      # -- the closure is the static files, darkhttpd (~100 KiB) and the
      # window. This is the output another flake should depend on.
      packages = forAll (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          inherit (bun2nix.packages.${system}.default) hook fetchBunDeps;
        in
        rec {
          # `vite build` reads the module through the @bgsvg alias and emits it
          # as a hashed asset beside the bundle, so what lands in $out is
          # self-contained: BGSVG_WASM is a build-time input and nothing more.
          site = pkgs.stdenv.mkDerivation {
            name = "wallpaper-studio-ui-site";

            # only what `bun run build` reads. node_modules/, dist/ and vendor/
            # are working-tree artefacts; letting them in would put the input
            # hash at the mercy of whatever was last built by hand.
            src = nixpkgs.lib.fileset.toSource {
              root = ./.;
              fileset = nixpkgs.lib.fileset.unions [
                ./index.html
                ./src
                ./tools # tsconfig type-checks it alongside src
                ./bun.lock
                ./bun.nix
                ./package.json
                ./tsconfig.json
                ./vite.config.ts
              ];
            };

            nativeBuildInputs = [ hook ];
            bunDeps = fetchBunDeps { bunNix = ./bun.nix; };

            # the same locked revision the devShell and the dev app export, so
            # no path can render through a module the lock does not name
            BGSVG_WASM = wallpaper-studio-svg.packages.${system}.bgsvg-wasm;

            # These displace the hook's own build and install, which compile a
            # bun executable. `build` is types + tsc --noEmit + vite build,
            # exactly what a developer runs, so a type error fails here too.
            buildPhase = ''
              runHook preBuild
              bun run build
              runHook postBuild
            '';

            installPhase = ''
              runHook preInstall
              cp -R dist $out
              runHook postInstall
            '';
          };

          default =
            let
              name = "wallpaper-studio-ui";
              # not 5173: an installed editor and a dev server should be able
              # to run at the same time
              port = "5174";
            in
            pkgs.writeShellApplication {
              inherit name;
              runtimeInputs = [ pkgs.darkhttpd ];
              text = windowed pkgs {
                inherit name port;
                # --no-listing: assets/ is an implementation detail
                serve = "darkhttpd ${site} --addr 127.0.0.1 --port ${port} --no-listing";

                # The store name of the site, which changes exactly when its
                # contents do -- so it is the cache key this URL should always
                # have carried. It has to be the URL, because no response header
                # can reach this: every file in the store shares one mtime, nix
                # normalises it to the epoch, and WebKit turns that 1970
                # Last-Modified into a heuristic freshness lifetime of decades.
                # It then serves the entry without asking the server at all, so
                # a Cache-Control saying otherwise is never read -- the response
                # carrying it is never fetched, and the window stays pinned to
                # whichever build it first saw. Only the document needs the key;
                # vite content-hashes every asset it emits.
                query = "?${builtins.baseNameOf site}";
              };
            };
        }
      );

      apps = forAll (
        pkgs:
        let
          system = pkgs.stdenv.hostPlatform.system;
          # `nix run .#dev` runs against your checkout rather than a built
          # derivation, deliberately: HMR is the whole point, and vite wants
          # node_modules and the module vendored into vendor/, neither of which
          # lives in the store. So this is the README's three commands in one.
          devServer =
            let
              name = "wallpaper-studio-ui-dev";
              port = "5173";
            in
            pkgs.writeShellApplication {
              inherit name;
              runtimeInputs = [ pkgs.bun ];
              text = ''
                if [ ! -f package.json ] || [ ! -f vite.config.ts ]; then
                  echo "${name}: run this from the wallpaper.studio.ui checkout" >&2
                  exit 1
                fi
                # the same locked revision the devShell exports, so `nix run .#dev`
                # and `nix develop` can never render through different modules
                export BGSVG_WASM="${wallpaper-studio-svg.packages.${system}.bgsvg-wasm}"
                [ -d node_modules ] || bun install
                bun run types
                ${windowed pkgs {
                  inherit name port;
                  serve = ''bun run dev --host 127.0.0.1 --port ${port} --strictPort "$@"'';
                }}
              '';
            };
        in
        rec {
          wallpaper-studio-ui = {
            type = "app";
            program = nixpkgs.lib.getExe self.packages.${system}.default;
          };
          default = wallpaper-studio-ui;
          dev = {
            type = "app";
            program = nixpkgs.lib.getExe devServer;
          };
        }
      );

      # package.json's `postinstall` keeps bun.nix level with bun.lock on the
      # path everyone takes; this is what fails closed when someone takes
      # another one -- a merge that touches bun.lock, a `bun install
      # --ignore-scripts`, a bun outside the devShell. It has to exist because
      # the drift is otherwise silent until `nix build .#site` hangs, which
      # names neither the file nor the cause.
      checks = forAll (pkgs: {
        bun-nix = pkgs.runCommand "bun-nix-matches-bun-lock"
          { nativeBuildInputs = [ bun2nix.packages.${pkgs.stdenv.hostPlatform.system}.default ]; }
          ''
            # --output-file, not a redirect: printing to stdout appends a
            # newline the file form does not, and the diff would never close
            bun2nix --lock-file ${./bun.lock} --output-file regenerated.nix
            diff -u ${./bun.nix} regenerated.nix || {
              echo "bun.nix is stale -- regenerate it with: bun2nix -o bun.nix" >&2
              exit 1
            }
            touch $out
          '';
      });

      devShells = forAll (pkgs: {
        default = pkgs.mkShell {
          # bun is runtime, package manager and TypeScript execution in one
          # binary; vite runs under it, since it is the better-proven path for
          # loading a WASM module and for HMR.
          #
          # bgsvg is here for `bgsvg --descriptor`, which feeds tools/drift.ts.
          # It does not render anything at development time -- the browser does
          # that, through the WASM module.
          #
          # bun2nix is what package.json's `postinstall` reaches for, so that
          # bun.nix follows bun.lock without anyone remembering to make it.
          packages = [
            pkgs.bun
            bun2nix.packages.${pkgs.stdenv.hostPlatform.system}.default
            wallpaper-studio-svg.packages.${pkgs.stdenv.hostPlatform.system}.default
          ];

          # the browser-callable module, from the same locked revision as the
          # bgsvg binary above -- vite.config.ts resolves the @bgsvg alias to it
          BGSVG_WASM = wallpaper-studio-svg.packages.${pkgs.stdenv.hostPlatform.system}.bgsvg-wasm;
        };
      });
    };
}
